# NumPy

[NumPy](https://numpy.org/) is a fundamental library for computation in Python.

Lets's compare regular Python lists and NumPy arrays.

In [51]:
import numpy as np

## Python list

In [1]:
# A list is created with [..,..]
myvals = [1.0, 2.0, 1.5]
myvals

[1.0, 2.0, 1.5]

In [2]:
type(myvals)

list

## Numpy 1D array (vector)

In [3]:
import numpy as np

myvals_np = np.array([1.2, 3.0, 4.0])

In [4]:
myvals_np

array([1.2, 3. , 4. ])

In [5]:
type(myvals_np)

numpy.ndarray

In [6]:
myvals_np.dtype

dtype('float64')

In [7]:
myvals_np.sum()

8.2

## Indexing

In [11]:
x = np.array([1.0,1.5, 2.0, 5.3]) 
x

array([1. , 1.5, 2. , 5.3])

In [12]:
x[1]

1.5

In [13]:
x[-1]

5.3

In [34]:
x[1] = 2.0 # modify the second value in the array
x

array([0., 2., 0., 0., 0.])

## Slicing

In [14]:
x[:2]

array([1. , 1.5])

## Math operations

Python is a general purpose language *not* designed with numerical computing in mind.

However, NumPy is designed to for numerical computing!

In [19]:
[1.2, 4.5] + [2.3, 4.3] # is this the result you expected??

[1.2, 4.5, 2.3, 4.3]

In [21]:
np.array([1.2, 4.5]) + np.array([2.3, 4.3]) 

array([3.5, 8.8])

In [171]:
np.array([1.2, 4.5]) * np.array([2.3, 4.3]) 

array([ 2.76, 19.35])

*Note for Matlab users, all operators such as `*` are element wise*

In [149]:
np.array([1.2, 4.5]) @ np.array([2.3, 4.3]) # in case you actually wanted to do a dot product

22.11

In [173]:
x = np.arange(5, 100, 5)
x

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [174]:
x.dtype # Integers!

dtype('int32')

In [175]:
x + 1 # add 1!

array([ 6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86,
       91, 96])

In [176]:
x = x + 3.0 # add a float to some integers, can we do that?
x

array([ 8., 13., 18., 23., 28., 33., 38., 43., 48., 53., 58., 63., 68.,
       73., 78., 83., 88., 93., 98.])

In [177]:
x.dtype # but now it became floats!

dtype('float64')

In [26]:
xr = np.random.random(10)
xr

array([0.82208304, 0.39317031, 0.71957261, 0.88895704, 0.51835599,
       0.2077102 , 0.80497636, 0.29904463, 0.26454055, 0.02991816])

In [27]:
xr.mean()

0.4948328893638917

In [28]:
xr.std()

0.28459880131751586

In [167]:
xr.max()

0.8889570351075812

In [29]:
xr - xr.mean()

array([ 0.32725015, -0.10166258,  0.22473972,  0.39412415,  0.0235231 ,
       -0.28712269,  0.31014347, -0.19578826, -0.23029234, -0.46491473])

In [178]:
xn = np.random.normal(loc=5.0, scale=2.0, size=100)
xn[30] = 99.0

In [181]:
mu = xn.mean()
sigma = xn.std()

xn[xn < mu - 3*sigma]

array([], dtype=float64)

In [182]:
xn[xn > mu + 3*sigma]

array([99.])

## Missing values (delete values)

NumPy has support for missing values.

In [41]:
y = np.random.random(10)
y

array([0.4756384 , 0.37056605, 0.48418933, 0.13842115, 0.16743762,
       0.36887873, 0.96338779, 0.35276924, 0.30977033, 0.6759752 ])

In [45]:
y[5:] = np.nan
y

array([0.4756384 , 0.37056605, 0.48418933, 0.13842115, 0.16743762,
              nan,        nan,        nan,        nan,        nan])

In [46]:
y.mean()

nan

In [47]:
np.nanmean(y)

0.3272505106683373

In [170]:
y * np.pi

array([1.49426209, 1.16416757, 1.52112565, 0.43486288, 0.5260208 ,
              nan,        nan,        nan,        nan,        nan])

## Boolean indexing

In [55]:
z = np.random.normal(loc=0.0, scale=3.0, size=10)

z_sorted = np.sort(z)
z_sorted

array([-4.08323864, -2.60874875, -1.38407103, -1.19227269, -0.68775294,
       -0.11558183,  1.08069393,  1.43845625,  2.6493312 ,  4.04633678])

In [56]:
z<0.0

array([False,  True,  True, False, False,  True,  True, False,  True,
        True])

In [57]:
z_sorted<0.0

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False])

In [58]:
z_sorted[z_sorted<0.0]

array([-4.08323864, -2.60874875, -1.38407103, -1.19227269, -0.68775294,
       -0.11558183])

In [59]:
z_sorted[z_sorted<0.0] = 0.0

In [60]:
z_sorted

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 1.08069393, 1.43845625, 2.6493312 , 4.04633678])

In [63]:
np.where(z<0.0)

(array([1, 2, 5, 6, 8, 9], dtype=int64),)

In [194]:
xn = np.random.normal(loc=5.0, scale=2.0, size=100)

xn[30] = 99.0 # outlier

median = np.median(xn)
sigma = xn.std()

In [197]:
sigma # sample std affected by outlier

9.595003363999345

In [187]:
xn[xn > median + 3*sigma] # but 1 abnormally high value

array([99.])

In [190]:
xn[xn > median + 3*sigma] = np.nan

In [193]:
np.nanstd(xn) # much closer to the true std==2.0

1.9942298376147203

## 2D arrays

In [102]:
X = np.array([
              [0.0, 1.0, 2.0],
              [3.0, 4.0, 5.0]
])
    

In [103]:
X

array([[0., 1., 2.],
       [3., 4., 5.]])

In [104]:
X.shape

(2, 3)

In [105]:
nrows = X.shape[0]
nrows

2

In [106]:
ncols = X.shape[1]
ncols

3

In [107]:
X[0,0]

0.0

In [108]:
X[1,1]

4.0

In [109]:
X[-1,-1]

5.0

In [110]:
X[0,:]

array([0., 1., 2.])

In [111]:
X[0]

array([0., 1., 2.])

In [112]:
X.mean()

2.5

In [113]:
colmeans = X.mean(axis=0)
colmeans

array([1.5, 2.5, 3.5])

In [114]:
colmeans.shape

(3,)

In [115]:
rowmeans = X.mean(axis=1)
rowmeans

array([1., 4.])

In [130]:
X - colmeans

array([[-1.5, -1.5, -1.5],
       [ 1.5,  1.5,  1.5]])

In [131]:
X - rowmeans

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

[NumPy broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html) (detailed explanation of how arrays can be used in expressions)

In [134]:
R = rowmeans[:, np.newaxis] # add a new dimension to create a 2D array
R

array([[1.],
       [4.]])

In [146]:
np.expand_dims(rowmeans, 1) # same result

array([[1.],
       [4.]])

In [135]:
X.shape

(2, 3)

In [136]:
R.shape

(2, 1)

In [132]:
X - R

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.]])

## Reshaping

In [118]:
x = X.flatten()

In [119]:
x

array([0., 1., 2., 3., 4., 5.])

In [120]:
x.reshape(2,3)

array([[0., 1., 2.],
       [3., 4., 5.]])